from __future__ import annotations

import json
import shlex
import time
from typing import ClassVar, Literal, override

from harbor.agents.base import BaseAgent
from harbor.agents.capabilities import AgentCapabilities
from harbor.agents.options import AgentOptions
from harbor.environments.base import BaseEnvironment
from harbor.models.agent.context import AgentContext
from pydantic import Field


class FakeAgentOptions(AgentOptions):
    behavior: Literal["success", "nonzero", "sleep", "memory", "fail_once"] = "success"
    sleep_seconds: float = Field(default=30.0, ge=0)
    allocation_mb: int = Field(default=1024, ge=1)


class FakeAgent(BaseAgent):
    """Deterministic provider-free agent used by Harbor Docker acceptance."""

    capabilities = AgentCapabilities(windows=False)
    options_model = FakeAgentOptions
    lifecycle_events: ClassVar[list[dict[str, str | float]]] = []

    @classmethod
    def clear_lifecycle_events(cls) -> None:
        cls.lifecycle_events.clear()

    @staticmethod
    @override
    def name() -> str:
        return "fake-agent"

    @override
    def version(self) -> str:
        return "0.1.0"

    @override
    async def setup(self, environment: BaseEnvironment) -> None:
        return None

    @override
    async def run(
        self,
        instruction: str,
        environment: BaseEnvironment,
        context: AgentContext,
    ) -> None:
        self.lifecycle_events.append(
            {
                "trial_id": str(self.context_id),
                "session_id": str(self.session_id),
                "environment_session_id": environment.session_id,
                "started_at": time.monotonic(),
            }
        )
        if self.options.behavior == "fail_once":
            attempts = sum(
                event["session_id"] == str(self.session_id)
                for event in self.lifecycle_events
            )
            if attempts == 1:
                raise RuntimeError("fake fail-once failure")

        if self.options.behavior == "nonzero":
            result = await environment.exec(command="exit 17")
            raise RuntimeError(f"fake nonzero exit: {result.return_code}")
        if self.options.behavior == "sleep":
            result = await environment.exec(
                command=f"sleep {self.options.sleep_seconds}"
            )
            if result.return_code != 0:
                raise RuntimeError(f"fake sleep failed: {result.return_code}")
        if self.options.behavior == "memory":
            result = await environment.exec(
                command=(
                    "python -c "
                    + shlex.quote(
                        f"data = bytearray({self.options.allocation_mb} * 1024 * 1024); "
                        "[data[i] = 1 for i in range(0, len(data), 4096)]; print(len(data))"
                    )
                )
            )
            if result.return_code != 0:
                raise RuntimeError(
                    f"fake memory allocation failed: {result.return_code}"
                )

        payload = {
            "schema_version": "agent-output.v1",
            "record_id": "fake-record-001",
            "status": "completed",
            "answer": {
                "short_text": "fake answer",
                "full_text": "fake answer generated by the Harbor acceptance adapter",
            },
            "artifacts": [],
            "session_evidence": {
                "adapter": self.name(),
                "instruction_bytes": len(instruction),
            },
            "failure": None,
        }
        output_path = "/logs/agent/agent-output.v1.json"
        command = (
            "mkdir -p /logs/agent && printf '%s' "
            f"{shlex.quote(json.dumps(payload, sort_keys=True))} > {output_path}"
        )
        result = await environment.exec(command=command)
        if result.return_code != 0:
            raise RuntimeError(
                f"fake agent output command failed: {result.stderr or result.return_code}"
            )
        context.metadata = {"agent_output_path": output_path, "adapter": self.name()}
